@dataProtector101_HostAddress = http://localhost:5210

POST {{dataProtector101_HostAddress}}/protect?data=hello
Accept: application/json

###

POST {{dataProtector101_HostAddress}}/unprotect?data=CfDJ8KifiklQuVdLugHYC-wEMX_VA1b5oQv16CfbGVLEQ4kDMGRZrAgoh8xMmhRCtwYupvB18lWHmHN1oQVDwFWEorcHpr70YZMVJb__KF9c3Dzd5M6Dk4I3uU3RO1bglAh1qA
Accept: application/json
